import type { Metadata } from "next";
import "./css/globals.css";
import "./css/navbar.css";
import "./css/bg.css";
import Nav from 'nav';
import Script from "next/script";

export const metadata: Metadata = {
  title: "VISIONARA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <Script src="https://cdn.lordicon.com/lordicon.js"></Script>
      </head>
      <body>
        {children}
        <Nav/>
      </body>
    </html>
  );
}
