import type { Metadata } from "next";
import "./css/globals.css";
import "./css/navbar.css";
import "./css/bg.css";
import Nav from 'nav';

export const metadata: Metadata = {
  title: "VISIONARA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        {children}
        <Nav/>
      </body>
    </html>
  );
}
